### ISSUE TITLE
Excellent Work

### ISSUE THREAD

**Issue by Jonatthu** [JacekKosciesza/StarWars#5]
Sorry but I could not stop myself to tell you that this is a wonderful work, thanks a lot to take your time on create this project for teach us.

I will close this issue, please provide your twitter

**Comment by JacekKosciesza** [comment]
Thank you very much for your kind words. I wish I had more time for this project, but I'm super busy right now with new career opportunities.

**Comment by hubert-associates** [comment]
I'd like to second this, and greatly encourage you to finish your bucket list :-) ... for example the master library has now added mutations to their doc and (old) example ...
